runtime: python310

entrypoint: streamlit run app.py --server.port=8080 --server.enableCORS=false

instance_class: F2  # Puedes ajustar esto según los recursos que necesites

env_variables:
  OPENAI_API_KEY: "{{ secrets.OPENAI_API_KEY }}"
